export const orderList = [
    {
        id: 1,
        nome_Cliente: 'Adelia Prado',
        data: '14 de dezembro',
        quantidade_Salgados: 10,
        bolo: true,
        preco: "R$ 10,00",
        evento: "Casamento",
        anotacoes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sit amet posuere nisi. Aenean fringilla diam vel elit ultricies, ac pretium libero eleifend. Duis eu dolor venenatis, pulvinar nisl eu, iaculis magna. Nunc faucibus sed erat sed hendrerit. Praesent quam lectus, gravida ac lectus ut, porta tristique massa. Maecenas semper facilisis sapien sit amet mattis.",
    },
    {
        id: 2,
        nome_Cliente: 'Conceição Evaristo',
        data: '16 de dezembro',
        quantidade_Salgados: 10,
        bolo: true,
        preco: "R$ 10,00",
        evento: "Aniversario",
        anotacoes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sit amet posuere nisi. Aenean fringilla diam vel elit ultricies, ac pretium libero eleifend. Duis eu dolor venenatis, pulvinar nisl eu, iaculis magna. Nunc faucibus sed erat sed hendrerit. Praesent quam lectus, gravida ac lectus ut, porta tristique massa. Maecenas semper facilisis sapien sit amet mattis.",
    },
    {
        id: 3,
        nome_Cliente: 'Fernando Pessoa',
        data: '16 de dezembro',
        quantidade_Salgados: 10,
        bolo: true,
        preco: "R$ 10,00",
        evento: "Festa",
        anotacoes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sit amet posuere nisi. Aenean fringilla diam vel elit ultricies, ac pretium libero eleifend. Duis eu dolor venenatis, pulvinar nisl eu, iaculis magna. Nunc faucibus sed erat sed hendrerit. Praesent quam lectus, gravida ac lectus ut, porta tristique massa. Maecenas semper facilisis sapien sit amet mattis.",
    },
    {
        id: 4,
        nome_Cliente: 'Adelia Prado',
        data: '20 de dezembro',
        quantidade_Salgados: 10,
        bolo: true,
        preco: "R$ 10,00",
        evento: "Aniversario",
        anotacoes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sit amet posuere nisi. Aenean fringilla diam vel elit ultricies, ac pretium libero eleifend. Duis eu dolor venenatis, pulvinar nisl eu, iaculis magna. Nunc faucibus sed erat sed hendrerit. Praesent quam lectus, gravida ac lectus ut, porta tristique massa. Maecenas semper facilisis sapien sit amet mattis.",
    },
    {
        id: 5,
        nome_Cliente: 'Manuel Bandeira',
        data: '21 de dezembro',
        quantidade_Salgados: 10,
        bolo: true,
        preco: "R$ 10,00",
        evento: "Aniversario",
        anotacoes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sit amet posuere nisi. Aenean fringilla diam vel elit ultricies, ac pretium libero eleifend. Duis eu dolor venenatis, pulvinar nisl eu, iaculis magna. Nunc faucibus sed erat sed hendrerit. Praesent quam lectus, gravida ac lectus ut, porta tristique massa. Maecenas semper facilisis sapien sit amet mattis.",
    },
    {
        id: 6,
        nome_Cliente: 'Gonçalves Dias',
        data: '21 de dezembro',
        quantidade_Salgados: 10,
        bolo: true,
        preco: "R$ 10,00",
        evento: "Outro",
        anotacoes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sit amet posuere nisi. Aenean fringilla diam vel elit ultricies, ac pretium libero eleifend. Duis eu dolor venenatis, pulvinar nisl eu, iaculis magna. Nunc faucibus sed erat sed hendrerit. Praesent quam lectus, gravida ac lectus ut, porta tristique massa. Maecenas semper facilisis sapien sit amet mattis.",
    },
    {
        id: 7,
        nome_Cliente: 'Machado de Assis',
        data: '21 de dezembro',
        quantidade_Salgados: 10,
        bolo: true,
        preco: "R$ 10,00",
        evento: "Festa",
        anotacoes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sit amet posuere nisi. Aenean fringilla diam vel elit ultricies, ac pretium libero eleifend. Duis eu dolor venenatis, pulvinar nisl eu, iaculis magna. Nunc faucibus sed erat sed hendrerit. Praesent quam lectus, gravida ac lectus ut, porta tristique massa. Maecenas semper facilisis sapien sit amet mattis.",
    },
    {
        id: 8,
        nome_Cliente: 'Machado de Assis',
        data: '22 de dezembro',
        quantidade_Salgados: 10,
        bolo: true,
        preco: "R$ 10,00",
        evento: "Festa",
        anotacoes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sit amet posuere nisi. Aenean fringilla diam vel elit ultricies, ac pretium libero eleifend. Duis eu dolor venenatis, pulvinar nisl eu, iaculis magna. Nunc faucibus sed erat sed hendrerit. Praesent quam lectus, gravida ac lectus ut, porta tristique massa. Maecenas semper facilisis sapien sit amet mattis.",
    },
    {
        id: 9,
        nome_Cliente: 'Machado de Assis',
        data: '25 de dezembro',
        quantidade_Salgados: 10,
        bolo: true,
        preco: "R$ 10,00",
        evento: "Outro",
        anotacoes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sit amet posuere nisi. Aenean fringilla diam vel elit ultricies, ac pretium libero eleifend. Duis eu dolor venenatis, pulvinar nisl eu, iaculis magna. Nunc faucibus sed erat sed hendrerit. Praesent quam lectus, gravida ac lectus ut, porta tristique massa. Maecenas semper facilisis sapien sit amet mattis.",
    },
    {
        id: 10,
        nome_Cliente: 'Machado de Assis',
        data: '25 de dezembro',
        quantidade_Salgados: 10,
        bolo: true,
        preco: "R$ 10,00",
        evento: "Festa",
        anotacoes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sit amet posuere nisi. Aenean fringilla diam vel elit ultricies, ac pretium libero eleifend. Duis eu dolor venenatis, pulvinar nisl eu, iaculis magna. Nunc faucibus sed erat sed hendrerit. Praesent quam lectus, gravida ac lectus ut, porta tristique massa. Maecenas semper facilisis sapien sit amet mattis.",
    },
];